import { createClient } from "@/lib/supabase/server";
import { isDemoMode } from "@/lib/env";

export type AgentItem={id:string;display_name:string;description:string;role:string;status:string;autonomy_level:number;last_run_at:string|null;current_task:string|null;tasks_today:number};
export type TaskItem={id:string;title:string;description:string|null;type:string;status:string;priority:string;reason:string|null;expected_impact:string|null;assigned_agent_id:string|null;agent_name:string|null;objective_title:string|null;created_at:string;output:unknown;error:unknown};
export type ApprovalItem={id:string;task_id:string;status:string;risk_level:string;reason:string;expected_impact:string|null;proposed_change:unknown;created_at:string;task_title:string;agent_name:string};
export type KnowledgeItem={id:string;title:string;content:string;type:string;source:string|null;created_at:string};

const agentSeeds:AgentItem[]=[
  ["00000000-0000-0000-0000-000000000101","Sofía","Chief Marketing Officer","cmo",2],["00000000-0000-0000-0000-000000000102","Mateo","Market Intelligence","market_intelligence",1],["00000000-0000-0000-0000-000000000103","Valentina","Social Media Director","social_media_director",1],["00000000-0000-0000-0000-000000000104","Bruno","Content Strategist","content_strategist",1],["00000000-0000-0000-0000-000000000105","Clara","Copywriter","copywriter",1],["00000000-0000-0000-0000-000000000106","Emilia","Creative Director","creative_director",1],["00000000-0000-0000-0000-000000000107","Tomás","Analytics","analytics",1],["00000000-0000-0000-0000-000000000108","Vera","Marketing Auditor","marketing_auditor",1],
].map(([id,name,description,role,level],i)=>({id:String(id),display_name:String(name),description:String(description),role:String(role),status:"active",autonomy_level:Number(level),last_run_at:i<2?new Date(Date.now()-i*30*60_000).toISOString():null,current_task:i===0?"Revisión diaria de marketing":i===1?"Revisar señales de mercado":null,tasks_today:i<2?i+1:0}));
const taskSeeds:TaskItem[]=[
  {id:"00000000-0000-0000-0000-000000000201",title:"Revisión diaria de marketing",description:"Revisar objetivos, prioridades y trabajo pendiente.",type:"cmo.daily_review",status:"completed",priority:"high",reason:"Rutina programada de coordinación",expected_impact:"Mantener al equipo alineado",assigned_agent_id:agentSeeds[0].id,agent_name:"Sofía",objective_title:"Aumentar registros calificados un 30%",created_at:new Date(Date.now()-45*60_000).toISOString(),output:{reviewed:["objectives","queue","approvals"]},error:null},
  {id:"00000000-0000-0000-0000-000000000202",title:"Revisar señales de mercado",description:"Identificar cambios y oportunidades relevantes.",type:"market.review_signals",status:"queued",priority:"medium",reason:"Delegada por Sofía",expected_impact:"Detectar oportunidades tempranas",assigned_agent_id:agentSeeds[1].id,agent_name:"Mateo",objective_title:"Aumentar registros calificados un 30%",created_at:new Date(Date.now()-35*60_000).toISOString(),output:null,error:null},
  {id:"00000000-0000-0000-0000-000000000203",title:"Aprobar brief de campaña “Vuelta a la rutina”",description:"Validar el enfoque editorial antes de producción.",type:"campaign.brief",status:"waiting_approval",priority:"high",reason:"El cambio afectará la comunicación pública",expected_impact:"Activar una campaña coordinada",assigned_agent_id:agentSeeds[3].id,agent_name:"Bruno",objective_title:"Aumentar registros calificados un 30%",created_at:new Date(Date.now()-12*60_000).toISOString(),output:null,error:null},
];
const approvalSeeds:ApprovalItem[]=[{id:"00000000-0000-0000-0000-000000000301",task_id:taskSeeds[2].id,status:"requested",risk_level:"medium",reason:"Validar el enfoque antes de delegar producción",expected_impact:"Habilita la campaña sin publicar ni gastar presupuesto",proposed_change:{artifact:"campaign brief",side_effect:false},created_at:new Date(Date.now()-12*60_000).toISOString(),task_title:taskSeeds[2].title,agent_name:"Bruno"}];
const knowledgeSeeds:KnowledgeItem[]=[{id:"k1",title:"Perfil de la empresa",content:"Northstar Urban ayuda a equipos a simplificar sus operaciones comerciales.",type:"company",source:"onboarding",created_at:new Date().toISOString()},{id:"k2",title:"ICP — Líder de operaciones",content:"Busca visibilidad, velocidad y menos trabajo manual. Objeción principal: tiempo de implementación.",type:"persona",source:"onboarding",created_at:new Date().toISOString()},{id:"k3",title:"Guía de voz",content:"Clara, segura, directa y útil. Evitar superlativos no demostrables.",type:"brand",source:"brand kit",created_at:new Date().toISOString()}];

async function context(){if(isDemoMode||!process.env.NEXT_PUBLIC_SUPABASE_URL)return null;const db=await createClient();const{data:{user}}=await db.auth.getUser();if(!user)return null;const{data:m}=await db.from("organization_members").select("organization_id,organizations(name)").eq("user_id",user.id).limit(1).maybeSingle();return m?{db,orgId:m.organization_id,orgName:((m.organizations as unknown as {name:string}|null)?.name??"Organización")}:null;}
export async function getAgents(){const ctx=await context();if(!ctx)return{mode:"demo" as const,orgName:"Northstar Urban",items:agentSeeds};const{data}=await ctx.db.from("agents").select("id,display_name,description,role,status,autonomy_level,last_run_at").eq("organization_id",ctx.orgId).order("display_name");const{data:tasks}=await ctx.db.from("tasks").select("assigned_agent_id,title,status,created_at").eq("organization_id",ctx.orgId).gte("created_at",new Date(new Date().setHours(0,0,0,0)).toISOString()).limit(200);return{mode:"live" as const,orgName:ctx.orgName,items:(data??[]).map(a=>({...a,current_task:(tasks??[]).find(t=>t.assigned_agent_id===a.id&&t.status==="running")?.title??null,tasks_today:(tasks??[]).filter(t=>t.assigned_agent_id===a.id).length})) as AgentItem[]};}
export async function getTasks(){const ctx=await context();if(!ctx)return{mode:"demo" as const,orgName:"Northstar Urban",items:taskSeeds};const{data}=await ctx.db.from("tasks").select("id,title,description,type,status,priority,reason,expected_impact,assigned_agent_id,created_at,output,error,agents(display_name),objectives(title)").eq("organization_id",ctx.orgId).order("created_at",{ascending:false}).limit(100);return{mode:"live" as const,orgName:ctx.orgName,items:(data??[]).map(t=>({...t,agent_name:(t.agents as unknown as {display_name:string}|null)?.display_name??null,objective_title:(t.objectives as unknown as {title:string}|null)?.title??null})) as TaskItem[]};}
export async function getApprovals(){const ctx=await context();if(!ctx)return{mode:"demo" as const,orgName:"Northstar Urban",items:approvalSeeds};const{data}=await ctx.db.from("approvals").select("id,task_id,status,risk_level,reason,expected_impact,proposed_change,created_at,tasks(title,agents(display_name))").eq("organization_id",ctx.orgId).order("created_at",{ascending:false}).limit(100);return{mode:"live" as const,orgName:ctx.orgName,items:(data??[]).map(a=>{const task=a.tasks as unknown as {title:string;agents:{display_name:string}|null}|null;return{...a,task_title:task?.title??"Tarea",agent_name:task?.agents?.display_name??"Agente"};}) as ApprovalItem[]};}
export async function getKnowledge(){const ctx=await context();if(!ctx)return{mode:"demo" as const,orgName:"Northstar Urban",items:knowledgeSeeds};const{data}=await ctx.db.from("knowledge_items").select("id,title,content,type,source,created_at").eq("organization_id",ctx.orgId).order("created_at",{ascending:false}).limit(100);return{mode:"live" as const,orgName:ctx.orgName,items:(data??[]) as KnowledgeItem[]};}
