import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowDown,CheckCircle2,FlaskConical } from "lucide-react";
import { DashboardShell } from "@/components/dashboard-shell";
import { StatusPill,WorkspacePage } from "@/components/workspace-page";
import { CampaignRunButton } from "@/components/campaign-run-button";
import { ApprovalActions } from "@/components/approval-actions";
import { getCampaignDetail } from "@/features/campaigns/data";

const tabs=["overview","strategy","research","audience","channels","content-plan","activity"] as const;
const labels:Record<(typeof tabs)[number],string>={overview:"Overview",strategy:"Strategy",research:"Research",audience:"Audience",channels:"Channels","content-plan":"Content Plan",activity:"Activity"};
function Strings({items}:{items:string[]|null|undefined}){return items?.length?<ul className="campaign-list">{items.map(item=><li key={item}>{item}</li>)}</ul>:<p className="panel-empty">Todavía no hay información para esta sección.</p>}

export default async function CampaignDetailPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{tab?:string}>}){const{id}=await params;const query=await searchParams;const active=tabs.includes(query.tab as (typeof tabs)[number])?query.tab as (typeof tabs)[number]:"overview";const data=await getCampaignDetail(id);if(!data)notFound();const c=data.campaign;const objective=c.objectives as unknown as {title:string;description?:string;metric?:string;target?:number}|null;const runnable=["draft","strategy"].includes(c.status)&&data.role!=="viewer";
  return <DashboardShell activePath="/campaigns" organizationName={data.orgName} demo={data.mode==="demo"}><WorkspacePage eyebrow={`CAMPAIGN BRAIN · v${c.strategy_version}`} title={c.name} description={c.summary||"Estrategia todavía no desarrollada."} action={runnable?<CampaignRunButton id={c.id} demo={data.mode==="demo"}/>:<StatusPill value={c.status}/>}><nav className="campaign-tabs" aria-label="Secciones de campaña">{tabs.map(tab=><Link key={tab} className={active===tab?"active":""} href={`/campaigns/${id}?tab=${tab}`}>{labels[tab]}</Link>)}</nav>
  {active==="overview"&&<div className="campaign-overview"><section className="campaign-hero-panel"><header><StatusPill value={c.status}/><span>{Math.round((c.confidence??0)*100)}% confianza · {c.strategy_provider??"sin provider"}</span></header><div className="campaign-graph"><div><small>OBJECTIVE</small><strong>{objective?.title??c.business_goal}</strong></div><ArrowDown/><div><small>CAMPAIGN</small><strong>{c.name}</strong></div><ArrowDown/><div><small>AUDIENCE</small><strong>{data.audience?.name??c.target_audience??"Por definir"}</strong></div><ArrowDown/><div className="graph-split"><span>{data.angles.length} ángulos</span><span>{data.channels.filter(item=>item.enabled).length} canales</span></div></div></section><section className="strategy-completeness"><h3>Strategy completeness</h3>{[["Research",Boolean(data.research)],["Audience",Boolean(data.audience)],["Channels",data.channels.length>0],["Pillars",data.pillars.length>0],["Angles",data.angles.length>0]].map(([label,done])=><div key={String(label)}><CheckCircle2 size={15} className={done?"done":""}/><span>{label}</span><b>{done?"Complete":"Pending"}</b></div>)}</section>{data.approval&&<section className="campaign-approval"><span>HUMAN CONTROL</span><h3>{data.approval.status==="requested"?"Campaign strategy ready":"Decision recorded"}</h3><p>Sofía propone aprobar la base estratégica v{c.strategy_version}. Esto no publica, programa ni gasta presupuesto.</p>{data.approval.status==="requested"&&<ApprovalActions id={data.approval.id} demo={data.mode==="demo"}/>} {data.approval.decision_note&&<blockquote>{data.approval.decision_note}</blockquote>}</section>}<section className="detail-panel wide"><h3>Why did Spectro create this campaign?</h3><dl className="facts"><div><dt>Objective</dt><dd>{objective?.title??c.business_goal}</dd></div><div><dt>Agents involved</dt><dd>Sofía · Mateo · Valentina · Bruno</dd></div><div><dt>Research used</dt><dd>{data.research?.research_mode==="external"?"External research":"Knowledge-based research"}</dd></div><div><dt>Prompt</dt><dd>{c.strategy_prompt_version??"Pending"}</dd></div><div><dt>Activity</dt><dd>{data.activity.length} audited entries loaded</dd></div></dl></section></div>}
  {active==="strategy"&&<div className="strategy-grid">{[["Business goal",c.business_goal],["Audience",c.target_audience],["Problem",c.problem],["Promise",c.promise],["Core message",c.core_message],["Positioning",c.positioning],["Creative thesis",c.creative_thesis],["CTA",c.primary_cta]].map(([label,value])=><section key={label}><span>{label}</span><p>{value||"Por definir"}</p></section>)}<section className="wide"><span>Supporting messages</span><Strings items={data.messaging?.supporting_messages}/></section><section><span>Value propositions</span><Strings items={data.messaging?.value_propositions}/></section><section><span>Proof points</span><Strings items={data.messaging?.proof_points}/></section></div>}
  {active==="research"&&<div className="research-grid"><section className="research-disclosure"><FlaskConical size={20}/><div><strong>{data.research?.research_mode==="external"?"External research":"Knowledge-based research"}</strong><p>{data.research?.research_mode==="external"?"Incluye fuentes externas identificadas.":"Sintetizado desde Brand, Products, Personas y Knowledge. No se presenta como navegación web."}</p></div></section><section><span>WHAT WE KNOW</span><h3>Contexto y señales</h3><Strings items={[...(data.research?.market_context??[]),...(data.research?.audience_pains??[]),...(data.research?.audience_language??[])]}/></section><section><span>WHAT WE ASSUME</span><h3>Supuestos explícitos</h3><Strings items={data.research?.assumptions}/></section><section><span>REQUIRES EXTERNAL RESEARCH</span><h3>Vacíos por investigar</h3><Strings items={data.research?.requires_external_research}/></section><section><span>OPPORTUNITIES</span><h3>Oportunidades</h3><Strings items={data.research?.opportunities}/></section><section><span>RISKS</span><h3>Riesgos</h3><Strings items={data.research?.risks}/></section></div>}
  {active==="audience"&&<div className="detail-grid"><section className="detail-panel wide"><span className="section-kicker">CAMPAIGN SEGMENT</span><h2>{data.audience?.name??"Por definir"}</h2><p>{data.audience?.description}</p><StatusPill value={data.audience?.awareness_level??"pending"}/></section>{[["Pains",data.audience?.pains],["Needs",data.audience?.needs],["Motivations",data.audience?.motivations],["Objections",data.audience?.objections]].map(([label,items])=><section className="detail-panel" key={String(label)}><h3>{String(label)}</h3><Strings items={items as string[]|undefined}/></section>)}</div>}
  {active==="channels"&&<div className="channel-grid">{data.channels.map(channel=><article className={channel.enabled?"channel-card recommended":"channel-card"} key={channel.id}><header><div><span>{channel.channel}</span><StatusPill value={channel.enabled?"recommended":"not_priority"}/></div><strong>{channel.score}<small>/100</small></strong></header><h3>{channel.role_in_campaign}</h3><p>{channel.reason}</p><dl><div><dt>Formats</dt><dd>{channel.formats.join(" · ")}</dd></div><div><dt>Frequency</dt><dd>{channel.publishing_frequency}</dd></div><div><dt>Confidence</dt><dd>{Math.round(channel.confidence*100)}%</dd></div></dl></article>)}</div>}
  {active==="content-plan"&&<div className="content-plan"><section className="pillar-panel"><header><div><span>CONTENT PILLARS</span><h2>Distribución editorial</h2></div><StatusPill value={data.pillarReport.coherent?"coherent":"review"}/></header>{data.pillars.map(pillar=><div className="pillar-row" key={pillar.id}><div><strong>{pillar.name}</strong><small>{pillar.description}</small></div><span>{pillar.weight}%</span><i><b style={{width:`${pillar.weight}%`}}/></i></div>)}<p>{data.pillarReport.message}</p></section><section className="angle-panel"><span>CREATIVE ANGLES</span><h2>Hipótesis para M02.2</h2>{data.angles.map(angle=><article key={angle.id}><header><h3>{angle.name}</h3><small>{Math.round(angle.confidence*100)}%</small></header><p>{angle.description}</p><dl><div><dt>Pain</dt><dd>{angle.audience_pain}</dd></div><div><dt>Promise</dt><dd>{angle.promise}</dd></div><div><dt>Formats</dt><dd>{angle.recommended_formats.join(" · ")}</dd></div></dl></article>)}</section></div>}
  {active==="activity"&&<div className="campaign-activity">{data.activity.map(item=><article key={item.id}><span/><div><header><strong>{(item.agents as unknown as {display_name:string}|null)?.display_name??"System"}</strong><time>{new Date(item.created_at).toLocaleString("es-UY")}</time></header><p>{item.summary}</p><small>{item.action}</small></div></article>)}</div>}
  </WorkspacePage></DashboardShell>}
