import { createClient,type SupabaseClient } from "@supabase/supabase-js";
import { afterAll,beforeAll,describe,expect,it } from "vitest";
import { assertSafeRemoteTestEnvironment,remoteTestsConfigured } from "../helpers/remote-test-guard";
import { runCampaignBrainForOrganization } from "@/server/campaigns/workflow";

const run=remoteTestsConfigured(["SUPABASE_TEST_URL","SUPABASE_TEST_SERVICE_KEY","NEXT_PUBLIC_SUPABASE_URL","NEXT_PUBLIC_SUPABASE_ANON_KEY","SUPABASE_SERVICE_ROLE_KEY","CRON_SECRET"]);
let db:SupabaseClient;let organizationId="";let campaignId="";
describe.skipIf(!run)("Campaign Brain persisted workflow",()=>{
  beforeAll(async()=>{assertSafeRemoteTestEnvironment();db=createClient(process.env.SUPABASE_TEST_URL!,process.env.SUPABASE_TEST_SERVICE_KEY!,{auth:{persistSession:false}});const org=await db.from("organizations").insert({name:"M02 Integration",slug:`m02-${crypto.randomUUID()}`}).select("id").single();if(org.error)throw org.error;organizationId=org.data.id;const objective=await db.from("objectives").insert({organization_id:organizationId,title:"Generate qualified demand",metric:"leads",target:200,status:"active"}).select("id").single();if(objective.error)throw objective.error;await db.from("brands").insert({organization_id:organizationId,name:"M02 Brand",forbidden_claims:["guaranteed"]});await db.from("agents").insert([{organization_id:organizationId,role:"cmo",display_name:"Sofía",autonomy_level:2},{organization_id:organizationId,role:"market_intelligence",display_name:"Mateo",autonomy_level:1},{organization_id:organizationId,role:"social_media_director",display_name:"Valentina",autonomy_level:1},{organization_id:organizationId,role:"content_strategist",display_name:"Bruno",autonomy_level:1}]);const campaign=await db.from("campaigns").insert({organization_id:organizationId,objective_id:objective.data.id,name:"M02 Campaign",slug:`m02-campaign-${crypto.randomUUID()}`,business_goal:"Generate qualified demand",created_by_type:"system"}).select("id").single();if(campaign.error)throw campaign.error;campaignId=campaign.data.id;},30_000);
  afterAll(async()=>{if(organizationId)await db.from("organizations").delete().eq("id",organizationId);});
  it("runs Sofia → Mateo → Valentina → Bruno → ready",async()=>{const result=await runCampaignBrainForOrganization(organizationId,campaignId,crypto.randomUUID());expect(result.report.completed).toBe(5);expect(result.status).toBe("ready");const [campaign,tasks,research,channels,pillars,angles,approval,version]=await Promise.all([db.from("campaigns").select("status,strategy_version").eq("id",campaignId).single(),db.from("tasks").select("type,status").eq("campaign_id",campaignId),db.from("campaign_research").select("research_mode").eq("campaign_id",campaignId).single(),db.from("campaign_channels").select("channel,enabled").eq("campaign_id",campaignId),db.from("campaign_content_pillars").select("weight").eq("campaign_id",campaignId),db.from("campaign_angles").select("id").eq("campaign_id",campaignId),db.from("approvals").select("status").eq("campaign_id",campaignId).single(),db.from("campaign_strategy_versions").select("version,provider,prompt_version").eq("campaign_id",campaignId).single()]);expect(campaign.data).toMatchObject({status:"ready",strategy_version:1});expect(tasks.data?.map(item=>item.type)).toEqual(["campaign.strategy.draft","campaign.research","campaign.channel_strategy","campaign.content_plan","campaign.strategy.finalize"]);expect(tasks.data?.every(item=>item.status==="completed")).toBe(true);expect(research.data?.research_mode).toBe("knowledge_based");expect(channels.data?.some(item=>item.enabled)).toBe(true);expect(pillars.data?.reduce((sum,item)=>sum+Number(item.weight),0)).toBe(100);expect(angles.data?.length).toBeGreaterThan(0);expect(approval.data?.status).toBe("requested");expect(version.data).toMatchObject({version:1,provider:"mock",prompt_version:"campaign-final-brief.v1"});},30_000);
});
