"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

export function CampaignCreateForm({objectives,demo}:{objectives:Array<{id:string;title:string;metric:string;target:number}>;demo:boolean}){
  const router=useRouter();const[busy,setBusy]=useState(false);const[error,setError]=useState("");
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);const payload={objectiveId:String(form.get("objectiveId")),name:String(form.get("name")||"")||undefined,specificAudience:String(form.get("specificAudience")||""),startDate:String(form.get("startDate")||"")||null,endDate:String(form.get("endDate")||"")||null,budget:form.get("budget")?Number(form.get("budget")):null,constraints:String(form.get("constraints")||"").split("\n").map(item=>item.trim()).filter(Boolean),developStrategy:form.get("developStrategy")==="on"};
    if(demo){router.push("/campaigns/00000000-0000-0000-0000-000000000401");return;}const response=await fetch("/api/campaigns",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await response.json().catch(()=>null);if(response.ok&&result?.id){router.push(`/campaigns/${result.id}`);router.refresh();return;}setError(result?.message??"No pudimos crear la campaña.");setBusy(false);}
  return <form className="campaign-form" onSubmit={submit}><section><span className="step-number">01</span><div><h2>Objetivo de negocio</h2><p>Campaign Brain conserva esta relación durante toda la estrategia.</p><label>Objetivo<select name="objectiveId" required defaultValue=""><option value="" disabled>Seleccionar objetivo</option>{objectives.map(item=><option key={item.id} value={item.id}>{item.title} · {item.target} {item.metric}</option>)}</select></label></div></section><section><span className="step-number">02</span><div><h2>Contexto opcional</h2><p>Podés orientar a Spectro sin definir la estrategia por adelantado.</p><div className="field-grid"><label>Nombre de campaña<input name="name" placeholder="Spectro puede proponerlo"/></label><label>Presupuesto estimado<input name="budget" type="number" min="0" step="0.01" placeholder="Opcional"/></label><label>Inicio<input name="startDate" type="date"/></label><label>Fin<input name="endDate" type="date"/></label><label className="wide">Audiencia específica<textarea name="specificAudience" placeholder="Ej. dueños de empresas de 5–50 personas..."/></label><label className="wide">Restricciones, una por línea<textarea name="constraints" placeholder="No usar promesas absolutas"/></label></div></div></section><section className="strategy-option"><input id="developStrategy" name="developStrategy" type="checkbox" defaultChecked/><label htmlFor="developStrategy"><strong>Dejar que Spectro desarrolle la estrategia</strong><span>Sofía coordinará research, canales, pilares y brief mediante una ejecución manual segura.</span></label></section>{error&&<p className="form-error">{error}</p>}<footer><button type="button" className="secondary-button" onClick={()=>router.back()}>Cancelar</button><button className="primary-button" disabled={busy||!objectives.length}>{busy?"Construyendo estrategia…":"Crear campaña"}</button></footer></form>;
}
