import Link from "next/link";
import { ArrowRight, Bot, Check, ChevronRight, CircleAlert, Clock3, Ellipsis, ShieldCheck, Sparkles, Target, TrendingUp } from "lucide-react";
import type { HqData } from "@/features/dashboard/data";
import { relativeTime } from "@/features/dashboard/data";

export function MarketingHQ({data}:{data:HqData}) {
  const objective=data.objective; const approval=data.approval;
  return <div className="hq-page">
    <header className="topbar"><div><p className="eyebrow">CENTRO DE OPERACIONES {data.mode==="demo"&&<b className="demo-badge">DEMO MODE</b>}</p><h1>Marketing HQ</h1><p>Tu departamento autónomo, con actividad trazable y control humano.</p></div><div className="topbar-actions"><button className="icon-button" aria-label="Más opciones"><Ellipsis size={20}/></button><Link className="primary-button" href="/tasks"><Sparkles size={16}/> Crear tarea</Link><span className="user-avatar">HQ</span></div></header>
    <section className="system-strip" aria-label="Estado del sistema"><div><span className={data.health.healthy?"pulse-dot":"offline-dot"}/><strong>{data.health.healthy?"Sistema operativo":"Worker sin actividad registrada"}</strong><small>Último ciclo {relativeTime(data.health.lastDispatch)}</small></div><div className="strip-stats"><span><b>{data.counts.running}</b> trabajando</span><span><b>{data.counts.queued}</b> en cola</span><span><b>{data.counts.approval}</b> requiere atención</span></div></section>
    <div className="content-grid"><div className="primary-column">
      <section><div className="section-heading"><div><span>OBJETIVO PRINCIPAL</span><h2>El foco del equipo</h2></div></div>
        {objective?<article className="objective-card"><div className="objective-icon"><Target size={21}/></div><div className="objective-body"><div className="objective-title"><div><h3>{objective.title}</h3><p>{objective.metric}{objective.market?` · ${objective.market}`:""}</p></div><span>{objective.priority.toUpperCase()} PRIORIDAD</span></div><div className="progress-row"><div className="progress-track"><span style={{width:`${objective.baseline?Math.min(100,Math.round(objective.baseline/objective.target*100)):0}%`}}/></div><b>{objective.baseline?Math.round(objective.baseline/objective.target*100):0}%</b></div><div className="objective-meta"><span><strong>{objective.baseline??"—"}</strong> baseline</span><span><strong>{objective.target}</strong> objetivo</span><span><Clock3 size={14}/>{objective.deadline?new Date(objective.deadline).toLocaleDateString("es-UY"):"Sin fecha"}</span></div></div></article>:<EmptyState text="Crea el primer objetivo para darle foco al equipo."/>}
      </section>
      <section><div className="section-heading"><div><span>AGENTES</span><h2>Equipo en operación</h2></div><Link href="/agents">Ver equipo <ArrowRight size={15}/></Link></div>
        {data.agents.length?<div className="agent-grid">{data.agents.slice(0,4).map(agent=><Link href={`/agents/${agent.id}`} className="agent-card" key={agent.id}><div className={`agent-avatar ${agent.tone}`}>{agent.initials}<span className={agent.state.toLowerCase()}/></div><div className="agent-main"><h3>{agent.name}</h3><p>{agent.role}</p></div><span className={`state-pill ${agent.state.toLowerCase()}`}>{agent.state}</span><div className="agent-task"><small>AHORA</small><p>{agent.task}</p></div><ChevronRight className="agent-chevron" size={17}/></Link>)}</div>:<EmptyState text="Los agentes aparecerán al completar el onboarding."/>}
      </section>
      <section><div className="section-heading"><div><span>TRABAJO AUTÓNOMO</span><h2>Flujo de hoy</h2></div><Link href="/tasks">Ver todo <ArrowRight size={15}/></Link></div><div className="work-summary"><Metric icon={<Check size={17}/>} tone="success" value={data.counts.completed} label="Completadas"/><Metric icon={<Bot size={17}/>} tone="active" value={data.counts.running} label="Ejecutando"/><Metric icon={<Clock3 size={17}/>} tone="muted" value={data.counts.queued} label="En cola"/><Metric icon={<ShieldCheck size={17}/>} tone="warning" value={data.counts.approval} label="Aprobación"/><Metric icon={<CircleAlert size={17}/>} tone="danger" value={data.counts.failed} label="Fallidas"/></div></section>
    </div><aside className="attention-column">
      <section><div className="section-heading compact"><div><span>NECESITA TU ATENCIÓN</span><h2>Decisiones pendientes</h2></div><b className="count-badge">{data.counts.approval}</b></div>
        {approval?<article className="approval-card"><div className="approval-top"><span className="approval-icon"><ShieldCheck size={17}/></span><span className="risk-pill">RIESGO {approval.risk.toUpperCase()}</span></div><h3>{approval.title}</h3><p>{approval.reason}</p><div className="proposer"><span className="mini-avatar">{approval.agentName.slice(0,2).toUpperCase()}</span><div><strong>{approval.agentName}</strong><small>{approval.agentRole}</small></div></div><Link className="review-button" href="/approvals">Revisar solicitud <ArrowRight size={15}/></Link></article>:<EmptyState text="No hay aprobaciones, errores o bloqueos pendientes."/>}
      </section>
      <section className="activity-section"><div className="section-heading compact"><div><span>ACTIVIDAD RECIENTE</span><h2>Qué hizo tu equipo</h2></div></div>{data.activity.length?<div className="timeline">{data.activity.slice(0,5).map(item=><div className="timeline-item" key={item.id}><span className={`timeline-dot ${item.action.includes("failed")?"insight":"done"}`}>{item.action.includes("learning")?<TrendingUp size={11}/>:<Check size={11}/>}</span><div><p>{item.summary}</p><small>{relativeTime(item.createdAt)}</small></div></div>)}</div>:<EmptyState text="La actividad trazable aparecerá después de la primera ejecución."/>}<Link className="text-button" href="/tasks">Abrir registro de actividad <ArrowRight size={14}/></Link></section>
    </aside></div>
  </div>;
}

function Metric({icon,tone,value,label}:{icon:React.ReactNode;tone:string;value:number;label:string}) { return <div><span className={`metric-icon ${tone}`}>{icon}</span><p><b>{value}</b><small>{label}</small></p></div>; }
function EmptyState({text}:{text:string}) { return <div className="empty-state"><p>{text}</p></div>; }
