import { isDemoMode } from "@/lib/env";
import { getOrganizationContext } from "@/features/organizations/context";
import { pillarWeightReport } from "@/server/campaigns/schemas";

const demoId="00000000-0000-0000-0000-000000000401";
const demoCampaign={id:demoId,name:"Tu equipo de marketing coordinado",status:"ready",summary:"Una campaña educativa para mostrar cómo un sistema de marketing mantiene estrategia, contexto y control humano conectados.",business_goal:"Aumentar registros calificados un 30%",campaign_type:"integrated",target_audience:"Dueños y líderes de PyMEs de 5–50 personas",problem:"El marketing depende de trabajo manual fragmentado.",promise:"Coordinar una operación consistente sin multiplicar procesos.",positioning:"Spectro como sistema operativo de marketing.",core_message:"Tu marketing puede trabajar como un sistema coordinado.",creative_thesis:"Contrastar el caos de herramientas aisladas con una operación trazable.",primary_cta:"Descubrir Spectro",start_date:null,end_date:null,budget:null,priority:"high",confidence:.76,strategy_version:1,strategy_provider:"mock",strategy_prompt_version:"campaign-final-brief.v1",created_at:new Date().toISOString(),objective_id:"demo-objective",objectives:{title:"Aumentar registros calificados un 30%",metric:"qualified_leads",target:200},created_by_type:"user"};
const demoAudience={id:"a1",name:"Líderes de PyME",description:"Responsables de crecimiento que necesitan continuidad sin agregar complejidad.",pains:["Trabajo manual repetitivo","Marketing fragmentado"],needs:["Prioridades claras","Control humano"],motivations:["Crecer con consistencia"],objections:["Pérdida de control"],awareness_level:"solution_aware"};
const demoResearch={research_mode:"knowledge_based",market_context:["Los equipos pequeños necesitan continuidad."],audience_pains:demoAudience.pains,audience_language:["Necesito que esto sea más simple"],frequent_questions:["¿Cuánto control conservo?"],objections:demoAudience.objections,competitor_messages:[],content_patterns:["Educación práctica"],opportunities:["Explicar coordinación antes que automatización"],risks:["Usar claims sin evidencia"],recommended_angles:["Crecimiento sin contratar"],sources:[{type:"brand",label:"Spectro"}],assumptions:["La audiencia prioriza eficiencia"],requires_external_research:["Benchmarks por canal","Mensajes actuales de competidores"],confidence:.66};
const demoChannels=[{id:"c1",channel:"instagram",enabled:true,role_in_campaign:"Awareness + educación",objective:"Hacer visible el problema",audience_fit:"Alto",priority:"high",formats:["Reels","Carruseles","Stories"],publishing_frequency:"4 por semana",tone_adjustment:"Directo y visual",content_notes:"Sin métricas no verificadas",score:88,reason:"Combina alcance visual y educación.",confidence:.76},{id:"c2",channel:"linkedin",enabled:true,role_in_campaign:"Autoridad + consideración",objective:"Explicar decisiones",audience_fit:"Alto",priority:"high",formats:["Documento","Post educativo"],publishing_frequency:"3 por semana",tone_adjustment:"Consultivo",content_notes:"Argumentos operativos",score:84,reason:"La audiencia evalúa valor de negocio aquí.",confidence:.78},{id:"c3",channel:"x",enabled:false,role_in_campaign:"Escucha",objective:"Validar temas",audience_fit:"Bajo",priority:"low",formats:["Hilo"],publishing_frequency:"No definido",tone_adjustment:"Sintético",content_notes:"No priorizar",score:27,reason:"No hay señal suficiente.",confidence:.36}];
const demoPillars=[{id:"p1",name:"Educación",description:"Explicar el sistema",weight:30,objective:"Crear comprensión"},{id:"p2",name:"Problema",description:"Visibilizar fragmentación",weight:20,objective:"Generar relevancia"},{id:"p3",name:"Producto",description:"Mostrar controles",weight:20,objective:"Construir consideración"},{id:"p4",name:"Autoridad",description:"Demostrar criterio",weight:15,objective:"Generar confianza"},{id:"p5",name:"Prueba",description:"Evidencia verificable",weight:10,objective:"Reducir riesgo"},{id:"p6",name:"Conversión",description:"Invitar a conocer",weight:5,objective:"Capturar intención"}];
const demoAngles=[{id:"g1",name:"Crecimiento sin contratar",description:"Coordinar más sin inflar procesos",hypothesis:"La eficiencia abre una conversación de crecimiento",audience_pain:"Capacidad limitada",promise:"Escalar coordinación",recommended_formats:["Carrusel"],priority:"high",confidence:.78},{id:"g2",name:"Control humano",description:"Automatización con límites",hypothesis:"Mostrar controles reduce objeciones",audience_pain:"Pérdida de control",promise:"Automatizar decisiones seguras",recommended_formats:["FAQ","Reel"],priority:"medium",confidence:.75}];
const demoActivity=[{id:"l1",action:"campaign.strategy_ready",summary:"Sofía consolidó Campaign Brief v1",created_at:new Date().toISOString(),agents:{display_name:"Sofía"}},{id:"l2",action:"campaign.pillars_created",summary:"Bruno creó pilares y ángulos",created_at:new Date(Date.now()-60000).toISOString(),agents:{display_name:"Bruno"}},{id:"l3",action:"campaign.channel_strategy_created",summary:"Valentina priorizó canales",created_at:new Date(Date.now()-120000).toISOString(),agents:{display_name:"Valentina"}},{id:"l4",action:"campaign.research_completed",summary:"Mateo completó research interno",created_at:new Date(Date.now()-180000).toISOString(),agents:{display_name:"Mateo"}}];

export async function getCampaigns(){
  const ctx=isDemoMode?null:await getOrganizationContext();if(!ctx)return isDemoMode?{mode:"demo" as const,orgName:"Northstar Urban",items:[{...demoCampaign,channels:demoChannels.filter(item=>item.enabled).map(item=>item.channel),progress:100}]}:{mode:"live" as const,orgName:"Sin organización",items:[]};
  const[{data:campaigns},{data:channels}]=await Promise.all([ctx.db.from("campaigns").select("id,name,status,summary,business_goal,start_date,end_date,created_by_type,created_at,strategy_version,objective_id,objectives(title)").eq("organization_id",ctx.orgId).order("created_at",{ascending:false}).limit(50),ctx.db.from("campaign_channels").select("campaign_id,strategy_version,channel,enabled").eq("organization_id",ctx.orgId).eq("enabled",true).limit(350)]);
  const items=(campaigns??[]).map(campaign=>{const active=(channels??[]).filter(channel=>channel.campaign_id===campaign.id&&channel.strategy_version===campaign.strategy_version).map(channel=>channel.channel);const progress=[campaign.status!=="draft",["strategy","ready","active","paused","completed"].includes(campaign.status),campaign.strategy_version>0,active.length>0].filter(Boolean).length*25;return{...campaign,channels:active,progress};});
  return{mode:"live" as const,orgName:ctx.orgName,items};
}

export async function getCampaignObjectives(){const ctx=isDemoMode?null:await getOrganizationContext();if(!ctx)return isDemoMode?{mode:"demo" as const,orgName:"Northstar Urban",items:[{id:"00000000-0000-0000-0000-000000000501",title:"Aumentar registros calificados un 30%",metric:"qualified_leads",target:200}]}:{mode:"live" as const,orgName:"Sin organización",items:[]};const{data}=await ctx.db.from("objectives").select("id,title,metric,target").eq("organization_id",ctx.orgId).in("status",["draft","active"]).order("created_at",{ascending:false}).limit(50);return{mode:"live" as const,orgName:ctx.orgName,items:data??[]};}

export async function getCampaignDetail(id:string){
  if(isDemoMode){if(id!==demoId)return null;return{mode:"demo" as const,orgName:"Northstar Urban",role:"owner",campaign:demoCampaign,audience:demoAudience,research:demoResearch,channels:demoChannels,pillars:demoPillars,angles:demoAngles,messaging:{supporting_messages:["Cada pieza nace de un objetivo."],value_propositions:["Coordinación","Contexto","Control humano"],proof_points:["Tasks y runs persistentes"],objections:["La IA actuará sola"],objection_responses:[{objection:"La IA actuará sola",response:"M02.1 requiere acción humana y no publica."}],forbidden_claims:[]},activity:demoActivity,tasks:[],approval:{id:"00000000-0000-0000-0000-000000000301",status:"requested",decision_note:null,created_at:new Date().toISOString()},pillarReport:pillarWeightReport(demoPillars)};}
  const ctx=await getOrganizationContext();if(!ctx)return null;const{data:campaign}=await ctx.db.from("campaigns").select("*,objectives(title,description,metric,target,deadline)").eq("id",id).eq("organization_id",ctx.orgId).maybeSingle();if(!campaign)return null;const version=Math.max(1,campaign.strategy_version||1);
  const[audience,research,channels,pillars,angles,messaging,activity,tasks,approval]=await Promise.all([
    ctx.db.from("campaign_audiences").select("*").eq("campaign_id",id).eq("strategy_version",version).maybeSingle(),ctx.db.from("campaign_research").select("*").eq("campaign_id",id).eq("strategy_version",version).maybeSingle(),
    ctx.db.from("campaign_channels").select("*").eq("campaign_id",id).eq("strategy_version",version).order("score",{ascending:false}).limit(7),ctx.db.from("campaign_content_pillars").select("*").eq("campaign_id",id).eq("strategy_version",version).order("weight",{ascending:false}).limit(20),
    ctx.db.from("campaign_angles").select("*").eq("campaign_id",id).eq("strategy_version",version).order("confidence",{ascending:false}).limit(30),ctx.db.from("campaign_messaging_frameworks").select("*").eq("campaign_id",id).eq("strategy_version",version).maybeSingle(),
    ctx.db.from("activity_log").select("id,action,summary,metadata,created_at,agents(display_name)").eq("campaign_id",id).order("created_at",{ascending:false}).limit(50),ctx.db.from("tasks").select("id,title,type,status,created_at,agents(display_name)").eq("campaign_id",id).order("created_at").limit(20),
    ctx.db.from("approvals").select("id,status,decision_note,created_at").eq("campaign_id",id).order("created_at",{ascending:false}).limit(1).maybeSingle(),
  ]);
  return{mode:"live" as const,orgName:ctx.orgName,role:ctx.role,campaign,audience:audience.data,research:research.data,channels:channels.data??[],pillars:pillars.data??[],angles:angles.data??[],messaging:messaging.data,activity:activity.data??[],tasks:tasks.data??[],approval:approval.data,pillarReport:pillarWeightReport((pillars.data??[]) as Array<{weight:number}>)};
}
