import { describe,expect,it } from "vitest";
import { MockProvider } from "@/server/agents/mock-provider";
import { campaignDraftSchema,channelStrategySchema,contentPlanSchema,pillarWeightReport,researchReportSchema } from "@/server/campaigns/schemas";
import { validateBrandGuardrails } from "@/server/campaigns/guardrails";
import { campaignStatusAfterApproval,canTransitionCampaign,nextStrategyVersion } from "@/server/campaigns/state";
import type { AgentContext } from "@/server/agents/contracts";

function context(type:string,input:Record<string,unknown>={}):AgentContext{return{organizationId:"00000000-0000-0000-0000-000000000001",correlationId:"00000000-0000-0000-0000-000000000002",agent:{id:"00000000-0000-0000-0000-000000000003",role:"cmo",displayName:"Sofía",autonomyLevel:2,configuration:{}},task:{id:crypto.randomUUID(),organization_id:"00000000-0000-0000-0000-000000000001",title:type,description:null,type,status:"running",priority:"high",assigned_agent_id:"00000000-0000-0000-0000-000000000003",objective_id:null,parent_task_id:null,source_event_id:null,requires_approval:false,risk_level:"low",attempt_count:1,max_attempts:3,input:{campaignId:"00000000-0000-0000-0000-000000000004",campaignName:"Test campaign",strategyVersion:1,objectiveTitle:"Generate 200 leads",productNames:["Spectro"],personaNames:["SMB owner"],...input},idempotency_key:null,campaign_id:"00000000-0000-0000-0000-000000000004"}};}

describe("Campaign Brain domain",()=>{
  it("enforces the campaign lifecycle and revision rules",()=>{expect(canTransitionCampaign("draft","researching")).toBe(true);expect(canTransitionCampaign("draft","active")).toBe(false);expect(canTransitionCampaign("ready","strategy")).toBe(true);expect(campaignStatusAfterApproval("ready","rejected")).toBe("strategy");expect(campaignStatusAfterApproval("ready","approved")).toBe("ready");expect(nextStrategyVersion(2)).toBe(3);});
  it("reports pillar distributions without corrupting drafts",()=>{expect(pillarWeightReport([{weight:60},{weight:40}])).toMatchObject({total:100,coherent:true});expect(pillarWeightReport([{weight:30},{weight:20}])).toMatchObject({total:50,coherent:false});});
  it("blocks forbidden brand language deterministically",()=>{expect(validateBrandGuardrails({texts:["La plataforma más barata garantizada"],forbiddenWords:["barata"],forbiddenClaims:["garantizada"],campaignConstraints:[]})).toMatchObject({passed:false,violations:[{kind:"forbidden_word",value:"barata"},{kind:"forbidden_claim",value:"garantizada"}]});});
  it("validates every deterministic provider artifact and delegation",async()=>{const provider=new MockProvider();const draft=await provider.run(context("campaign.strategy.draft"));expect(campaignDraftSchema.safeParse(draft.output).success).toBe(true);expect(draft.delegatedTasks?.[0]?.type).toBe("campaign.research");const research=await provider.run(context("campaign.research"));expect(researchReportSchema.safeParse(research.output).success).toBe(true);expect(research.output.researchMode).toBe("knowledge_based");expect(research.delegatedTasks?.[0]?.type).toBe("campaign.channel_strategy");const channels=await provider.run(context("campaign.channel_strategy"));expect(channelStrategySchema.safeParse(channels.output).success).toBe(true);expect(channels.delegatedTasks?.[0]?.type).toBe("campaign.content_plan");const content=await provider.run(context("campaign.content_plan"));expect(contentPlanSchema.safeParse(content.output).success).toBe(true);expect(pillarWeightReport(content.output.pillars as Array<{weight:number}>).coherent).toBe(true);expect(content.delegatedTasks?.[0]?.type).toBe("campaign.strategy.finalize");});
});
